version: "3"

tasks:
  # build
  # dev
  # install
  # run-binary

  build:
    cmds:
      - go build main.go

  dev:
    cmds:
      - source .env
      - air -c .air.toml

  install:
    cmds:
      - go install ./...

  run-binary:
    cmds:
      - task prepare
      - ./main
